FROM php:7.2-apache

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN sed -i '/#LoadModule rewrite_module/s/^#//g' /etc/apache2/apache2.conf
RUN sed -i '/#LoadModule headers_module/s/^#//g' /etc/apache2/apache2.conf