version: '3.3'
services:
  CapDatos:
          image:  docker.io/bitnami/laravel:10
          ports:
          - "8083:8000"
          environment:
            - DB_HOST=185.60.40.210
            - DB_PORT=3306
            - DB_USERNAME=Aimar
            - DB_PASSWORD=12345678
            - DB_DATABASE=Aimar
          volumes:
            - ./CapDeDatos/:/app
          command: ["php", "artisan", "schedule:work"]
  # Plan B
  # capdatos:
  #         build: 
  #           context: ./
  #           dockerfile: Dockerfile
  #         ports:
  #         - "8083:80" 
  #         environment:
  #          - DB_HOST=185.60.40.210
  #          - DB_PORT=3306
  #          - DB_USERNAME=Aimar
  #          - DB_PASSWORD=12345678
  #          - DB_DATABASE=Aimar
  #         volumes:
  #         - ./CapturaDeDatosPHP/:/var/www/html
  APIWeb:
          image:  docker.io/bitnami/laravel:10
          ports:
          - "8086:8000"
          environment:
            - DB_HOST=185.60.40.210
            - DB_PORT=3306
            - DB_USERNAME=Aimar
            - DB_PASSWORD=12345678
            - DB_DATABASE=Aimar
          volumes:
            - ./APIWeb/:/app
  LAMP:
          image: httpd:latest
          ports:
          - "8082:80"
          volumes:
          - ./APP:/usr/local/apache2/htdocs/
  Inverso:
          image: nginx:latest
          ports:
          - "81:80"
          depends_on:
          - LAMP