version: '3.3'
services:
  #Imagen linux con .php y .js para nutrir la base de datos
  CapDatos:
          image:  ubuntu:22.04
          ports:
          - "8085:8000"
          #volumes:
          #- './NombreArchivo/:/carpetaMaquina'
  APIWeb:
          image:  docker.io/bitnami/laravel:10
          ports:
          - "8086:8000"
          environment:
            - DB_HOST=185.60.40.210
            - DB_PORT=3306
            - DB_USERNAME=Aimar
            - DB_PASSWORD=12345678
            - DB_DATABASE=Aimar
          volumes:
            - ./APIWeb/:/app
  LAMP:
          image: httpd:latest
          ports:
          - "8082:80"
  Inverso:
          image: nginx:latest
          ports:
          - "81:80"
          depends_on:
          - LAMP